# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-Play-MPG321
version:      0.001
version_from: lib/Audio/Play/MPG321.pm
installdirs:  site
requires:
    IO::Select:                    1.16
    IPC::Open2:                    1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
